### Create user

POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage":10000,
  "lng": 0,
  "lat": 0,
  "price": 14000
}
### Approve

PATCH  http://localhost:3000/reports/3
Content-Type: application/json

{
  "approved": true
}

### get estimate

GET  http://localhost:3000/reports?make=toyota&model=corolla&year=1982&mileage=1234&lng=0&lat=0



### Create user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "emailu876@email.com",
  "password": "password"
}

### Sign in user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "emailu876@email.com",
  "password": "password"
}

### Get user

GET http://localhost:3000/auth/1

### Get all users

GET http://localhost:3000/auth?email=email@email.com

### Delete user

DELETE  http://localhost:3000/auth/1

### Update user

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "email1@email.com"
}

### Get signes user

GET http://localhost:3000/auth/whoami


### Get signes user

POST http://localhost:3000/auth/signout
